Offering Search Query
=====================

....
query {
    offeringSearch(filter: OfferingSearchResultFilter){
        OfferingCourseSearchResult
    }
}
....

== Filter

|===
| Edvisor | B&L | Notes 

| offeringTypesIds
| -
| To look for courses you have to add `offeringTypesIds: 1`

| googlePlaceIds
| city, countryCode 
| You can send multiple places and a place can be a city or country. To get available options use `offeringSearchFilterOptions` query

| offeringCourseCategoryIds
| courseType
| You can send multiple categories, you can get availabe categories using `offeringSearchFilterOptions` and `offeringCourseCategories` query

| schoolIds
| institute
| You can look for multiple school ids. Please note that this referes to the campus

| startDate
| startDate
| 
|===

== Example 


.offeringSearchForCourseOfferingsQuery.gql
[source, graphql]
....
query offeringSearchForCourseOfferings(
  $agencyId: Int, 
  $nationalityId: Int, 
  $schoolIds: [Int], 
  $currentCountryId: Int, 
  $courseCategories: [Int], 
  $durationTypeId: Int, 
  $durationAmount: IntegerRangeInput, 
  $languageId: Int, 
  $locations: [String], 
  $startDate: DateOnlyRangeInput, 
  $age: IntegerRangeInput,
  $pagination: PaginationInput!
) {
  offeringSearch(filter: {
    offeringTypeIds: [1], 
    nationalityId: $nationalityId, 
    currentCountryId: $currentCountryId, 
    schoolIds: $schoolIds, 
    offeringCourseCategoryIds: $courseCategories, 
    durationTypeId: $durationTypeId, 
    durationAmount: $durationAmount, 
    googlePlaceIds: $locations, 
    startDate: $startDate, 
    agencyId: $agencyId, 
    pagination: $pagination,
    age: $age
  }) {
    ... on OfferingCourseSearchResult {
      offeringCourseSearchResultId: offeringId
      startDate
      durationAmount
      currencyId
      durationType {
        durationTypeId
        codeName
      }
      offering {
        offeringId
        name(languageId: $languageId)
        offeringTypeId
        defaultLanguageId
        offeringDescriptions {
          offeringDescriptionId
          languageId
          description
        }
        reqMinAge
        reqMaxAge
        reqMinDurationAmount
        reqMinDurationTypeId
        reqMaxDurationAmount
        reqMaxDurationTypeId
        offeringCourse {
          offeringCourseId: offeringId
          offeringCourseCategory {
            offeringCourseCategoryId
            codeName
          }
          offeringTimetableTemplate {
            offeringTimetableTemplateId
            hoursPerWeek
          }
          offeringStartDateDerived {
            startDate
          }
          offeringPriceTemplate {
            offeringPriceTemplateId
            offeringPrices {
              offeringPriceId
              minDuration
              maxDuration
              durationTypeId
              amountIsPerDuration
            }
          }
        }
        school {
          schoolId
          name
          googlePlaceId
          agencyRank
          schoolBannerFile {
            fileId
            url
          }
          googlePlace {
            googlePlaceId
            translation(languageId: $languageId)
          }
          schoolDurationTypeDefinitions {
            schoolDurationTypeDefinitionId
            durationTypeId
            definitionDurationTypeId
            definitionDuration
          }
        }
      }
    }
  }
}
....

.Variables
[source,json]
....
{
  "languageId":1,
  "pagination": {
    "limit": 25,
    "offset": 0
  }
}
....


