Offering Search FilterOptions
==============================

Query to look for existing options to search for courses. Returns a list of all schools (campuses), categories and googleplaces ids (cities, countries) thahave at least one course avilable

.offeringSearchFilterOptions.gql
[source, graphql]
....
query  {
  offeringSearchFilterOptions(filter: OfferingSearchFilterOptionsFilter){
    # OfferingSearchFilterOptionsResult
  }
}
....

NOTE: The query doesn't have arguments other than  `schoolIds` and doesn't have pagination.

== Example to get locations

The following query will return all locations where a course is offered. You can change locations name by sending a different `languageId`

.offeringSearchFilterOptionsForLocation.gql
[soruce,graphql]
....
query offeringSearchFilterOptionsForLocation($languageId: Int) {
  offeringSearchFilterOptions {
    schoolGooglePlaces {
      googlePlaceId
      countryId
      cityName: translation(languageId: $languageId)
      country {
        countryName: nameTranslation(languageId: $languageId)
      }
    }
  }
}
....

.Variables
[source,json]
....
{
    "languageId": 1
}
....


== Example to get schools (campuses)

Yu can also look for schools

.offeringSearchFilterOptionsForSchools.gql
[soruce,graphql]
....
query offeringSearchFilterOptionsForSchools {
  offeringSearchFilterOptions {
    schools{
      name
      schoolId
      schoolCompany{
        schoolCompanyId
        name
      }
    }
  }
}
....
